### ISSUE TITLE
mmcv版本问题

### ISSUE THREAD

**Issue by EiJuN-xmu** [Gengzigang/PCT#1]
我在执行指令`./tools/dist_train.sh configs/pct_[base/large/huge]_classifier.py 8`时，发生错误：`AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.`
接着我卸载当前版本的mmcv并下载2.0.0rc4版本，但是又出现错误：`ImportError: cannot import name 'Config' from 'mmcv'`，该如何解决呀

**Comment by EiJuN-xmu** [comment]
我的系统是ubuntu20.04

**Comment by Gengzigang** [comment]
Hi, this is because the latest version of MMPose has been updated, which installs version 1.x by default. However, this repo is using version 0.x. I just updated the requirements, mmpose==0.29.0, you can install it directly.

**Comment by EiJuN-xmu** [comment]
Solved, thanks very much!!!!!!!!

**Comment by JasOleander** [comment]
I installed those modules like you said mmpose==0.29.0 and mmcv==1.7.0 and mmdet==2.26.0. But I got the mmcv._ext error. How can solve that?

**Comment by gigasurgeon** [comment]
> I installed those modules like you said mmpose==0.29.0 and mmcv==1.7.0 and mmdet==2.26.0. But I got the mmcv._ext error. How can solve that?

you can solve it by adding the root path of this cloned repo on top of **PCT/vis_tools/demo_img_with_mmdet.py**

```
import sys
sys.path.append('/home/xyz/PCT')
```
