### ISSUE TITLE
information about the backbone

### ISSUE THREAD

**Issue by gmk11** [Gengzigang/PCT#10]
hi , can i have better information about the swin backbone you used ? Is your backbone a modified version of swin transformers? I tried to have the number of parameter of the backbone only and it turn out that it only contains 8000 parameters what is different from the one provided initially by Microsoft that is around a billion of parameter. Can you please give me more information about the swin backbone you used ? 
Number of parameters ?
FLOPs? (only the backbone)

**Comment by Gengzigang** [comment]
We use the official Swin backbone without any modifications. You can refer to the publicly available parameter and FLOPs. I believe there might be an issue with your statistics, as you may not have included the parameters of the frozen parameters.
