### ISSUE TITLE
Question about the dimension of token feature

### ISSUE THREAD

**Issue by PeiChiChen** [Gengzigang/PCT#16]
Hello, thanks for your attractive idea in this paper.
In the paper, the dimension of each token feature is H and the dimension of each embedding in codebook is N.
Is H equal to N?
Because in eq.2 we need to calculate the distance between these two vectors, the dimension should be same.
Looking forward to your reply!

**Comment by Gengzigang** [comment]
Hello, thank you for your interest in our work. Indeed, H is equal to N. We appreciate you pointing this out.

**Comment by PeiChiChen** [comment]
Thanks!
