### ISSUE TITLE
When training a classifier, don't freeze the weights of the decoder and codebook?

### ISSUE THREAD

**Issue by epleone** [Gengzigang/PCT#30]
hi, When training a classifier, don't freeze the weights of the decoder and codebook? I didn't find any steps in the code for freezing weights.

**Comment by KunmingS** [comment]
Hi epleone,

Do you find which code indicates the weight of the decoder and codebook has frozen?

**Comment by epleone** [comment]
@Kun-Ming 

Yes, I found it before. But it's been a long time. 

It might be [this line](https://github.com/Gengzigang/PCT/blob/6f356f6efd0859d958b9f5eb82b17cb4e4f0a70a/models/pct_head.py#L235).

**Comment by KunmingS** [comment]
@epleone 
Thanks! That makes sense.

**Comment by epleone** [comment]
Glad to help you.

**Comment by pchsu-hsupc** [comment]
hi, @epleone ,

Does this method (not freezing decoder and codebook )get better accuracy ? 

Cause I couldn't reach accuracy than heatmap base q_q

**Comment by epleone** [comment]
@Tommy-Hsu 
I'm not clear about this.

**Comment by pchsu-hsupc** [comment]
Forget about it.
I wasn't understanding code that time.
Now, it's clear. 
Thanks.
